version: '2.4'  # The last version of Docker Compose file format that directly supports mem_limit and cpus
services:
  counter-service:
    container_name: counter-service-exercise
    image: 939466156342.dkr.ecr.us-west-1.amazonaws.com/counter-service-dev:latest
    volumes:
      - ./data:/data
    ports:
      - "80:8080"
    restart: always
    mem_limit: 256M
    cpus: 0.5